# Generated by Django 5.0.6 on 2026-10-05 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stockitem",
            options={"ordering": ["name"]},
        ),
    ]
