# Generated by Django 5.0.6 on 2026-10-05 18:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agriculture", "0003_alter_activity_options_alter_crop_options_and_more"),
        ("finances", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sale",
            options={"ordering": ["-date", "-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="transaction",
            options={"ordering": ["-date", "-created_at"]},
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["crop", "date"], name="finances_sa_crop_id_f71ee0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["user", "transaction_type"],
                name="finances_tr_user_id_4ae168_idx",
            ),
        ),
    ]
