# Generated by Django 5.0.6 on 2026-10-05 18:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aiinteraction",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddIndex(
            model_name="aiinteraction",
            index=models.Index(
                fields=["user", "created_at"], name="ai_assistan_user_id_21b84b_idx"
            ),
        ),
    ]
