# Generated by Django 5.0.6 on 2026-10-05 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0002_alter_aiinteraction_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiinteraction",
            name="origin",
            field=models.CharField(
                choices=[
                    ("database", "Fiches Naatal Agro"),
                    ("database+web", "Fiches Naatal Agro et web vérifié"),
                    ("web", "Web vérifié"),
                    ("general", "Conseil général sans source"),
                ],
                default="general",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="aiinteraction",
            name="sources",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Sources citées : [{number, title, publisher, url, type}]",
            ),
        ),
    ]
