# Generated by Django 5.0.6 on 2026-10-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0003_origin_and_sources"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiinteraction",
            name="suggestions",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Questions de relance proposées à l'utilisateur",
            ),
        ),
    ]
