# Generated by Django 5.0.6 on 2026-06-27 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="fcm_token",
            field=models.CharField(
                blank=True,
                help_text="Firebase Cloud Messaging Token",
                max_length=255,
                null=True,
            ),
        ),
    ]
