# Generated by Django 5.0.6 on 2026-07-29 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_fcm_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("farmer", "Agriculteur"), ("buyer", "Acheteur B2B")],
                default="farmer",
                max_length=20,
            ),
        ),
    ]
