# Generated by Django 5.0.6 on 2026-08-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="main_crops",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
