# Generated by Django 5.0.6 on 2026-08-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='primary_crops',
            field=models.JSONField(blank=True, default=list, help_text="Liste des cultures principales (ex: ['riz', 'arachide'])"),
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.CharField(blank=True, choices=[('dakar', 'Dakar'), ('thies', 'Thiès'), ('saint_louis', 'Saint-Louis'), ('kaolack', 'Kaolack'), ('ziguinchor', 'Ziguinchor'), ('tambacounda', 'Tambacounda'), ('kolda', 'Kolda'), ('matam', 'Matam'), ('kaffrine', 'Kaffrine'), ('kedougou', 'Kédougou'), ('louga', 'Louga'), ('fatick', 'Fatick'), ('sedhiou', 'Sédhiou'), ('diourbel', 'Diourbel')], max_length=50, null=True),
        ),
    ]
