# Generated by Django 5.0.6 on 2026-10-05 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_date_of_birth_user_main_crops"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("farmer", "Agriculteur"), ("admin", "Administrateur")],
                default="farmer",
                max_length=20,
            ),
        ),
    ]
