# Generated by Django 5.0.6 on 2026-10-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="privacy_accepted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date d'acceptation de la politique de confidentialité",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="privacy_policy_version",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Version de la politique acceptée",
                max_length=20,
            ),
        ),
    ]
