# Generated by Django 5.0.6 on 2026-10-05 18:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agriculture", "0002_pestreport"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={"ordering": ["date"]},
        ),
        migrations.AlterModelOptions(
            name="crop",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="pestreport",
            options={"ordering": ["-date_reported"]},
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["crop", "date"], name="agriculture_crop_id_eff372_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="crop",
            index=models.Index(
                fields=["user", "status"], name="agriculture_user_id_d89877_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pestreport",
            index=models.Index(
                fields=["location", "date_reported"],
                name="agriculture_locatio_d7ae2c_idx",
            ),
        ),
    ]
