# Generated by Django 5.0.6 on 2026-10-05 20:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agriculture", "0003_alter_activity_options_alter_crop_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgronomicGuide",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("scientific_name", models.CharField(blank=True, max_length=120)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("legume", "Légume"),
                            ("cereale", "Céréale"),
                            ("legumineuse", "Légumineuse"),
                        ],
                        max_length=20,
                    ),
                ),
                ("summary", models.TextField()),
                (
                    "zones",
                    models.TextField(
                        blank=True, help_text="Zones de culture au Sénégal"
                    ),
                ),
                (
                    "cycle_days_min",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "cycle_days_max",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "calendar",
                    models.TextField(
                        blank=True,
                        help_text="Calendrier de semis, repiquage et récolte",
                    ),
                ),
                (
                    "soil_and_sowing",
                    models.TextField(
                        blank=True, help_text="Sol, préparation, semis, densité"
                    ),
                ),
                ("water_needs", models.TextField(blank=True)),
                ("fertilization", models.TextField(blank=True)),
                (
                    "pests_diseases",
                    models.JSONField(
                        blank=True, default=list, help_text="Liste de {name, advice}"
                    ),
                ),
                ("harvest", models.TextField(blank=True)),
                ("yield_info", models.TextField(blank=True)),
                (
                    "limitations",
                    models.TextField(
                        blank=True,
                        help_text="Limites et points à vérifier avant de s'appuyer sur la fiche",
                    ),
                ),
                (
                    "sources",
                    models.JSONField(
                        default=list, help_text="Liste de {title, publisher, year, url}"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
