# Generated by Django 5.0.6 on 2026-10-05 21:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agriculture", "0005_load_agronomic_guides"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="agronomicguide",
            name="aliases",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Autres noms que les utilisateurs emploient (pluriel, nom local) pour retrouver la fiche",
            ),
        ),
        migrations.AddField(
            model_name="agronomicguide",
            name="locally_edited",
            field=models.BooleanField(
                default=False,
                help_text="Modifiée depuis l'administration : le rechargement du fichier du dépôt ne l'écrase pas (sauf --force)",
            ),
        ),
        migrations.CreateModel(
            name="KnowledgeProposal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "field",
                    models.CharField(
                        choices=[
                            ("summary", "Présentation"),
                            ("zones", "Zones de culture"),
                            ("calendar", "Calendrier"),
                            ("soil_and_sowing", "Sol et semis"),
                            ("water_needs", "Eau"),
                            ("fertilization", "Fertilisation"),
                            ("harvest", "Récolte"),
                            ("yield_info", "Rendement"),
                            ("pests_diseases", "Maladies et ravageurs"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "pest_name",
                    models.CharField(
                        blank=True,
                        help_text="Obligatoire pour « Maladies et ravageurs »",
                        max_length=120,
                    ),
                ),
                ("proposed_text", models.TextField()),
                (
                    "quote",
                    models.TextField(
                        help_text="Extrait exact de la source qui justifie le texte proposé"
                    ),
                ),
                ("source_title", models.CharField(max_length=300)),
                ("source_publisher", models.CharField(max_length=200)),
                ("source_year", models.CharField(blank=True, max_length=40)),
                ("source_url", models.URLField(max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "À valider"),
                            ("approved", "Approuvée"),
                            ("rejected", "Rejetée"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("submitted_via", models.CharField(default="manual", max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_note", models.CharField(blank=True, max_length=300)),
                (
                    "guide",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposals",
                        to="agriculture.agronomicguide",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="agriculture_status_ff7996_idx",
                    )
                ],
            },
        ),
    ]
