# Generated by Django 5.0.6 on 2026-10-05 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agriculture", "0007_reload_guides_with_aliases"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agronomicguide",
            name="category",
            field=models.CharField(
                choices=[
                    ("legume", "Légume"),
                    ("cereale", "Céréale"),
                    ("legumineuse", "Légumineuse"),
                    ("fruit", "Fruit"),
                ],
                max_length=20,
            ),
        ),
    ]
