# Generated by Django 5.0.6 on 2026-07-26 11:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("LÉGUME", "Légume"),
                            ("FRUIT", "Fruit"),
                            ("CÉRÉALE", "Céréale"),
                            ("TUBERCULE", "Tubercule"),
                        ],
                        max_length=50,
                    ),
                ),
                ("current_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "trend_percentage",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("image_asset", models.CharField(max_length=255)),
                ("is_trending", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
