# Generated by Django 5.0.6 on 2026-07-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0003_presaleoffer_presalereservation"),
    ]

    operations = [
        migrations.AddField(
            model_name="market",
            name="closing_time",
            field=models.TimeField(default="18:00:00"),
        ),
        migrations.AddField(
            model_name="market",
            name="opening_time",
            field=models.TimeField(default="08:00:00"),
        ),
        migrations.AddField(
            model_name="market",
            name="rating",
            field=models.DecimalField(decimal_places=1, default=4.5, max_digits=3),
        ),
    ]
