# Generated by Django 5.0.6 on 2026-10-05 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0004_market_closing_time_market_opening_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="presalereservation",
            name="offer",
        ),
        migrations.RemoveField(
            model_name="presalereservation",
            name="buyer",
        ),
        migrations.DeleteModel(
            name="PreSaleOffer",
        ),
        migrations.DeleteModel(
            name="PreSaleReservation",
        ),
    ]
