# Generated by Django 5.0.6 on 2026-10-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0005_remove_presalereservation_offer_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="market",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="price",
            options={"ordering": ["-date", "product_name"]},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["name"]},
        ),
        migrations.AddIndex(
            model_name="price",
            index=models.Index(
                fields=["market", "product_name"], name="markets_pri_market__9ab0b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category"], name="markets_pro_categor_ac6643_idx"
            ),
        ),
    ]
