$dirs = @(
    "docs",
    "backend/core/settings",
    "backend/apps/users",
    "backend/apps/agriculture",
    "backend/apps/markets",
    "backend/apps/weather",
    "backend/apps/notifications",
    "backend/apps/ai_assistant",
    "backend/apps/analytics",
    "backend/shared/exceptions",
    "backend/shared/utils",
    "backend/shared/permissions",
    "mobile/lib/core/theme",
    "mobile/lib/core/routes",
    "mobile/lib/core/constants",
    "mobile/lib/core/network",
    "mobile/lib/features/auth",
    "mobile/lib/features/home",
    "mobile/lib/features/product",
    "mobile/lib/features/markets",
    "mobile/lib/features/map",
    "mobile/lib/features/ai",
    "mobile/lib/features/profile",
    "mobile/lib/shared/buttons",
    "mobile/lib/shared/cards",
    "mobile/lib/shared/dialogs",
    "mobile/lib/shared/loaders",
    "mobile/assets/images",
    "mobile/assets/icons",
    "mobile/assets/fonts",
    "web/src/core",
    "web/src/modules/dashboard",
    "web/src/modules/markets",
    "web/src/modules/analytics",
    "web/src/modules/users",
    "web/src/shared",
    "web/src/services",
    "infra/docker",
    "infra/nginx",
    "infra/postgres",
    "infra/ci-cd",
    "ai/prompts",
    "ai/services",
    "database",
    "tests/backend",
    "tests/mobile",
    "tests/integration",
    "scripts",
    ".github/workflows"
)

foreach ($dir in $dirs) {
    New-Item -ItemType Directory -Force -Path $dir | Out-Null
}

$files = @(
    "docs/00-Project-Charter.md",
    "docs/01-Vision.md",
    "docs/02-Product-Requirements.md",
    "docs/03-UX-UI.md",
    "docs/04-Architecture-System.md",
    "docs/05-Database-Design.md",
    "docs/06-Backend-API.md",
    "docs/07-Mobile-Flutter.md",
    "docs/08-Web-React.md",
    "docs/09-AI-System.md",
    "docs/10-Security.md",
    "docs/11-DevOps-Deployment.md",
    "docs/12-Project-Management.md",
    "docs/13-Roadmap.md",
    "backend/core/urls.py",
    "backend/core/asgi.py",
    "backend/core/wsgi.py",
    "backend/requirements.txt",
    "backend/manage.py",
    "mobile/lib/main.dart",
    "mobile/pubspec.yaml",
    "web/src/App.tsx",
    "web/package.json",
    "ai/prompts/farming_advice.txt",
    "ai/prompts/disease_detection.txt",
    "ai/prompts/market_prediction.txt",
    "ai/README.md",
    "database/erd.png",
    "database/migrations_notes.md",
    "database/seed_data.sql",
    "scripts/setup.sh",
    "scripts/deploy.sh",
    "scripts/seed.sh",
    "README.md",
    ".gitignore"
)

foreach ($file in $files) {
    New-Item -ItemType File -Force -Path $file | Out-Null
}
