# Generated by Django 5.0.6 on 2026-10-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="weatherdata",
            options={
                "ordering": ["-forecast_date"],
                "verbose_name_plural": "Weather data",
            },
        ),
        migrations.AddIndex(
            model_name="weatherdata",
            index=models.Index(
                fields=["location", "forecast_date"],
                name="weather_wea_locatio_6e2167_idx",
            ),
        ),
    ]
